### ISSUE TITLE
Support late binding

### ISSUE THREAD

**Issue by marvinhagemeister** [preactjs/preact-devtools#10]
The extension should successfully connect when the devtools is openend _after_ the page has loaded. For that to work we need to synchronously inject the renderer into the page. If I recall correctly, the only way to do that is via an ugly `XMLHttpRequest` hack. Grepping the `react-devtools` source should be enough to find it.

**Comment by AEnterprise** [comment]
i'm guessing this is also why closing and re-opening the dev tools after the page loaded makes it get stuck in ``connected, waiting for nodes to load``? until you reload the page?

**Comment by marvinhagemeister** [comment]
That's a different issue. Opened: https://github.com/preactjs/preact-devtools/issues/91 for that :+1: 

The original issue here is resolved by #90 . The devtools now reliably connect when they weren't open when the page was loaded.
