### ISSUE TITLE
Prop changes from the UI mutate existing props object

### ISSUE THREAD

**Issue by wnayes** [preactjs/preact-devtools#118]
I have a particular function component which holds a reference (`useRef`) to the last `props` that it received, in order to do some comparisons against the next `props` in an effect hook.

I found that prop updates from the devtools UI were not taking effect, and it turns out this was because the `renderer.ts` directly mutates the component props.

```
if (type === "props") {
	setIn((vnode.props as any) || {}, path.slice(), value);
}
```

In the course of normal JSX usage, my understanding is that it's atypical to be re-rendered with the same `props` object instance, and even more atypical for the same instance to be mutated inside.

So my proposal is: could we shallow copy the props here, and then mutate the shallow copy, to mimic a more standard re-render behavior?

I believe I've found that the React Devtools do this, as their [`setInProps`](https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/backend/legacy/renderer.js#L870) calls a [`copyWithSet`](https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/backend/utils.js#L58) method that performs a shallow copy.

**Comment by marvinhagemeister** [comment]
Good catch! Yup, we should do a shallow copy there and not mutate the original object :+1:
