### ISSUE TITLE
[FEATURE] DevTools show hook useState values

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [preactjs/preact-devtools#148]
i have code (webpack "react" alias "preact/compat" ) 

```javascript
import { useEffect, useState } from "react";


export default function Index() {

  const [x, setX] = useState(0)

  function plusX() {
    setX(x => x + 1)
  }

  return <div>
    <button onClick={ plusX }>x { x }</button>
  </div>
}
```

i click but i not see hook state:

![image](https://user-images.githubusercontent.com/60403187/79442540-59d93e00-7fe1-11ea-9138-d7fb97a4c3e0.png)

let's add this? react devtools have it =)

By the way, we can add all the hooks, and show for example useEffect hook and two functions, the effect function and the undo function, and dependencies. so that a person can see the code of functions and dependencies. play with them, etc. =)

in react-dev-tools this is not =) there only useState is displayed, but in 
Presct-dev-tools we can add function show information about all the hooks on right panel =)

Like this:
---
![image](https://user-images.githubusercontent.com/60403187/79447004-d7a04800-7fe7-11ea-8a40-399ba3b01c00.png)

**Comment by marvinhagemeister** [comment]
Thanks for reporting this! There is already an issue to track that which I'm already working on 👍

See #52
