### ISSUE TITLE
Search is unable to jump to the results in the tree view

### ISSUE THREAD

**Issue by ddayguerrero** [preactjs/preact-devtools#162]
### Bug Description

Given a long `vnode` tree (with a scroll view) with available search results, when pressing `Enter` the tree view does not jump to the referenced search result. This affects developer experience as it is hard to see what are the search results.

### Expected behaviour

The tree view should jump to the referenced search result as we press `Enter`. Making it easier to navigate across results.

### Steps to reproduce the bug

Testing with the Preact's website https://preactjs.com/guide/v10/components. This happens in my professional usage as well:

1- Go to https://preactjs.com/guide/v10/components
2- Open devtools (v0.4.0)

Here's a quick recording, please let me know if it could be clearer. Notice when I navigate through the results on `Enter`:

![preactdevtools-search](https://user-images.githubusercontent.com/6437556/79802755-8d440180-832e-11ea-95e3-36de88fb8fad.gif)

**Comment by marvinhagemeister** [comment]
Awesome, thanks for the detailed issue 👍 This shouldn't be hard to fix

**Comment by ddayguerrero** [comment]
🎉
