### ISSUE TITLE
iframe, "this page doesn't seem to be using Preact"

### ISSUE THREAD

**Issue by jflebeau** [preactjs/preact-devtools#207]
Saw in the release notes that iframes should work now, but I'm stil not able to use the tool to inspect a Preact widget embeded in dummy static html page. Anything I could be doing wrong?

**Comment by marvinhagemeister** [comment]
Not quite, the release notes are referring to corrected positions of the highlight overlay. It still required forwarding all events to the top `window` object.

Proper support for `iframes` is coming with #209 .
