### ISSUE TITLE
Can devtools remember filters

### ISSUE THREAD

**Issue by kenny-f** [preactjs/preact-devtools#246]
### Suggestion
Devtools to remember the component filters. 

### Steps to reproduce
- Open preact devtools
- Add some filters
- Close devtools
- Open devtools again
- All the filters are lost and one has to enter them all again

Would be good if it can somehow remember the filters. When working on the same project day in day out it would save a lot of time to not have to enter them everytime

**Comment by marvinhagemeister** [comment]
@kenny-f That's a great idea! Filters will now be saved with the next release 👍 Just submitted a new version to browser stores and it should be up in the next couple of days.

**Comment by kenny-f** [comment]
@marvinhagemeister wow, that was quick! Thanks a lot

**Comment by marvinhagemeister** [comment]
The new version is up in all browser stores and the browser will update to the version automatically 👍

**Comment by marvinhagemeister** [comment]
The filter values themselves are properly loaded on initial boot in the extension, but it looks like their not applied to the page on load.
