### ISSUE TITLE
Devtools v1.2.0 with preact 1.5.7 shadows throwing hooks

### ISSUE THREAD

**Issue by donkeyDau** [preactjs/preact-devtools#270]
Starting from 1.5.6 using hooks outside from `render` method preact throws. When using the preact-devtools in Firefox in v1.2.0 I see this error:

```
Uncaught (in promise) TypeError: c is null
    getComponentHooks map:1262
    getStatefulHooks map:1265
    __h map:3307
    m index.js:99
    d index.js:214
    s index.js:189
...
```

Disabling the preact-devtools I can see:
> Error: Hook can only be invoked from render methods.

**Comment by marvinhagemeister** [comment]
Thanks for reporting this. I'll check as soon as I'm home.

**Comment by marvinhagemeister** [comment]
@donkeyDau I'm unable to reproduce a crash like you described inside the devtools. Can you share the component/code that triggered it?

**Comment by donkeyDau** [comment]
Unfortunately it's company code ... I fiddled around for an hour but was not able to create a (not) working example. I think it's a combination of async loading (using `AsyncRoute` from [preact-async-route](https://github.com/prateekbh/preact-async-route) and [preact-router](https://github.com/preactjs/preact-router)) and `import { withApollo } from '@apollo/client/react/hoc';`. 

```
{
  "dependencies": {
    "@apollo/client": "3.2.5",
    "preact": "10.5.7",
    "preact-async-route": "2.2.1",
    "preact-router": "3.2.1"
  }
}
```

The causing code was:

``` 
class Map extends Component {
  leafletMap = useRef(null);
....
```

You can close the issue if I'm the only with this problem as I solved it by not using hooks outside the render method :)
