### ISSUE TITLE
Avoid using `unload` event listener on `window`.

### ISSUE THREAD

**Issue by pope** [preactjs/preact-devtools#275]
In https://github.com/preactjs/preact-devtools/blob/master/src/adapter/hook.ts#L146, an `unload` event listener is used. The problem is that attaching an event handler/listener to window or document's unload event prevents browsers from using in-memory page navigation caches, like [Firefox's Back-Forward cache](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/1.5/Using_Firefox_1.5_caching) or [WebKit's Page Cache](https://webkit.org/blog/516/webkit-page-cache-ii-the-unload-event/). Since this an extension - this penalty gets applied to every web page.

Instead, would it be possible to use the `pagehide` event handler? That does not tamper with the caches.

**Comment by marvinhagemeister** [comment]
TIL, wasn't aware that using the `unload` event blocks navigation caches 👍

**Comment by pope** [comment]
In what way are you interested in iFrame interactions and how `pagehide` works with them?

**Comment by marvinhagemeister** [comment]
The extension currently supports inspecting apps that run in iframes and not the main context. The name `pagehide` seems to suggest that it's bound to a page instead of a frame.

**Comment by pope** [comment]
Here's a silly app that logs that the `pagehide` event does get triggered on the iFrame's `window` when I remove the iFrame from a page: https://stackblitz.com/edit/js-u9ppkg?file=index.js. Of note, `pagehide` nor `unload` fire on the `iframe` element or the page's `window` object. Not sure if that's what you were concerned about or not though.

**Comment by devmattrick** [comment]
This also seems to confuse Lighthouse in Chrome's Dev Tools as it's complaining about the website registering one but is unable to find the source of it: 
![image](https://user-images.githubusercontent.com/5848320/103494512-0f585580-4dec-11eb-9d2f-3d739d0b4d91.png)

Took me a bit to figure out where it came from, but hopefully this helps others figure out why Lighthouse is complaining!

**Comment by marvinhagemeister** [comment]
@pope That's perfect. It only needs to be triggered in the same frame where the devtools connection has been established, so we're all good 👍
