### ISSUE TITLE
Devtools only shows one hook per component

### ISSUE THREAD

**Issue by mindgrub-egottlieb** [preactjs/preact-devtools#278]
In the Elements explorer in devtools, the Hooks list only shows the first hook invoked in each component, regardless of how many hooks are actually used in the component. 

I'm able to reproduce this on both Chrome and Firefox, and I have uninstalled/reinstalled/updated the devtools extension. At first, I thought maybe it had something to do with the custom hooks I was using, but it still happens in the example below, which only uses native hooks. This issue started for me a few months ago.

Here's a CSB on the latest preact version: https://codesandbox.io/s/preact-devtools-hooks-not-appearing-78vu9

https://user-images.githubusercontent.com/43963655/104352558-d0558e80-54d4-11eb-955c-946f2b6a6bc6.mov

**Comment by marvinhagemeister** [comment]
Some first thouhgts: For some reason the `options._hook` is only called once and not for every hook. Not sure why yet, but that's a hot trail.

**Comment by marvinhagemeister** [comment]
Alright, found the root cause! The codesandbox helped a ton in finding it. Thank you so much for filing this issue 🎉

Have to run now, I'll PR a fix with a test case tomorrow 👍

**Comment by mindgrub-egottlieb** [comment]
Sounds good, thanks a ton for the quick response!
