### ISSUE TITLE
Highlight updates ignores memoized components

### ISSUE THREAD

**Issue by Pringels** [preactjs/preact-devtools#284]
The highlight updates feature seems to ignore components wrapped in `memo()`. Sorry in advance if that has been raised as an issue before. I could not find anything similar. 

## Expected Behavior
Highlights should only appear for components that were actually updated. 

**Screenshot from React devtools:**
![image](https://user-images.githubusercontent.com/4850521/111616458-349d1300-87e2-11eb-826b-9cf3b041e329.png)

✅  **React sandbox:** https://codesandbox.io/s/upbeat-fog-lw6r3
✅  **React test link:** https://lw6r3.csb.app/

## Current Behavior
Preact devtools highlights components that _didn't_ get updated. In my example code I force this by
always returning `true` from a component wrapped in `memo()`. 

**Screenshot from Preact devtools:**
![image](https://user-images.githubusercontent.com/4850521/111615555-2c90a380-87e1-11eb-907b-7ee52d759391.png)

✅  **Preact sandbox:** https://codesandbox.io/s/cool-smoke-bm1or (devtools does not work in preview tab. Open link instead)
✅  **Preact test link:** https://bm1or.csb.app/

## Detailed Description
Perhaps am I missing something? I tried looking through the docs and github issues to find information related to this.
Also I just assumed that that Preact devtools highlights should work exactly like React devtools highlights. Is this a flawed expectation?

**Comment by Pringels** [comment]
@marvinhagemeister I will gladly create a PR for this if you would be willing to point me in the right direction :) 
Not sure how easy it is to fix but yeah I would appreciate it!

**Comment by marvinhagemeister** [comment]
Sorry that it took so long. This was fixed by #388 as the highlight updates feature shares the same branch as the other stuff. With recent refactors where we now track which components actually rendered this got a lot easier to implement 👍

**Comment by Pringels** [comment]
Thank you!
