### ISSUE TITLE
Just get "Connected, listening for Preact operations"

### ISSUE THREAD

**Issue by carderne** [preactjs/preact-devtools#299]
Using the sample code from [this comment](https://github.com/preactjs/preact-devtools/issues/283#issuecomment-801906635), running on `light-server` localhost.

```html
<!DOCTYPE html>
<html>
  <body>  
    <div id="app"></div>
    <script type="module">
      import "https://cdn.skypack.dev/preact/debug";

      import { h, Component, render } from "https://cdn.skypack.dev/preact";
      import htm from "https://cdn.skypack.dev/htm";

      const html = htm.bind(h);

      const app = html`<h1>Hello World!</h1>`;
      render(app, document.getElementById("app"));
    </script>
  </body>
</html>
```

In both Chrome and Firefox (with uBlock disabled), I get the following message:
> Connected, listening for Preact operations...
> If this message doesn't go away Preact started rendering before devtools was initialized. You can fix this by adding the `preact/debug` or `preact/devtools` import at the top of your entry file.

What am I doing wrong?

**Comment by marvinhagemeister** [comment]
Thanks for filing a bug report. By default the devtools will filter out anything that isn't a component. In the snippet above we only render DOM nodes. The devtools doesn't receive any messages because they've been filtered out, so it assumes that nothing was sent.

Adding a component somewhere makes it show up in devtools:

```diff
<!DOCTYPE html>
<html>
  <body>
    <div id="app"></div>
    <script type="module">
      import "https://cdn.skypack.dev/preact/debug";

      import { h, Component, render } from "https://cdn.skypack.dev/preact";
      import htm from "https://cdn.skypack.dev/htm";

      const html = htm.bind(h);

-      const app = html`<h1>Hello World!</h1>`;
+      const App = () => html`<h1>Hello World!</h1>`;
-      render(app, document.getElementById("app"));
+      render(html`<${App} />`, document.getElementById("app"));
    </script>
  </body>
</html>
```

I'm leaving this open as we should be able to print a better message there. Something that hints to the user that the active filters leads to no nodes being shown.

**Comment by carderne** [comment]
Thanks for the clarification! What I'm actually trying to do is use Preact with [microbundle](https://gist.github.com/developit/078bb85420b4a47828f303f9929495d1) and I somehow wasn't including "preact/debug" in the correct way.

I've now done it as follows:

```js
// microbundle entry point
export * from "preact/debug";
export * from "preact";
export * from "htm/preact";
...
```

```js
// my app's entry point
import { html, render } from "./preact-bundle.js";
...
```

And it's working fine.
