### ISSUE TITLE
Display content of ES6 Map props

### ISSUE THREAD

**Issue by sebastiano-barrera** [preactjs/preact-devtools#300]
Hi!

I'm a relative beginner in JS and SPA development, and I was surprised to find that the Preact Devtools extension (in Firefox at least) doesn't show the content for props of type ES6 Map, but only the names of its methods (`clear`, `set`, `delete`, `add`). Here's what I see (look at `session.document.windows.objects`, for example):

![image](https://user-images.githubusercontent.com/7526491/118886432-39bd3200-b8f9-11eb-88a3-18d8eae9e3bc.png)

Is this a bug, or missing feature? Is it planned? If it isn't, what do you think of it? Could you guide me in implementing it?

Thanks!

**Comment by sebastiano-barrera** [comment]
DAMN that was fast!

Thank you so much! Looking forward to using preact more and maybe contributing one day.

**Comment by marvinhagemeister** [comment]
Likewise, thanks for taking the time to file a report! I've just submitted a new version of the extension to browser stores. Should be live in a few days (Firefox is already up).
