### ISSUE TITLE
Error with JSS useContext

### ISSUE THREAD

**Issue by ahoenerBE** [preactjs/preact-devtools#314]
I'm using Preact with JSS, and I can't seem to inspect one of my components

![Screen Shot 2021-08-18 at 6 21 31 PM](https://user-images.githubusercontent.com/84148896/129979761-40f6c098-dc8c-4183-b4b6-36f86390c9b8.png)

VirtualizedItemTable contains JSS styles with the useStyles() hook
```
const useStyles = createUseStyles({
     innerContainer: {
         display: 'flex',
         flex: '1 1 auto',
         border: '1px solid',
         paddingBottom: '1px'
     },
     table: {},
     header: {
         display: 'flex',
         alignItems: 'center',
         // paddingTop: '.5em',
     },
 });
```

When attempting to view the component, I get the following on firefox
![Screen Shot 2021-08-18 at 6 18 21 PM](https://user-images.githubusercontent.com/84148896/129980364-19394930-59e9-4235-b990-9afc7ef7e672.png)

and this on Chrome

![Screen Shot 2021-08-18 at 6 17 49 PM](https://user-images.githubusercontent.com/84148896/129980377-90f63802-4736-421c-8b1c-37df7fad2f97.png)

Removing the JSS and just using imported CSS works fine

**Comment by alpacone** [comment]
Same error with `goober`. I made a demo: https://codesandbox.io/s/goober-preact-devtools-tr71r
Works fine if you remove `useTheme` from `setup`.

**Comment by marvinhagemeister** [comment]
Thank you @ahoenerBE for the report and @alpacone for the repro case. Just pushed a new version into the review queue and it should be up shortly. The fist was [already in `main`](https://github.com/preactjs/preact-devtools/pull/304) but I missed creating a new version earlier, sorry for the inconvenience!
