### ISSUE TITLE
don't expand component tree by default

### ISSUE THREAD

**Issue by oleks12345** [preactjs/preact-devtools#333]
In large codebase expanding all components makes devtools hard to navigate

**Comment by marvinhagemeister** [comment]
Interesting, that's the first time I'm hearing of that. What leads to the component tree being difficult to navigate? Does it contain lots of wrapper components that create so much visual noise or are these "actual" components?

**Comment by oleks12345** [comment]
using library for components makes some noise but that is not a big problem.
Biggest problem is when looking into component that has many children - for example table row, I don't need to have all items open (when every items has its own children (some of them nested)), when I want to look at last item.  
Inspect on element doesn't navigate for me to right component on list (it changes only details on right to selected component), so finding stuff is hard
