### ISSUE TITLE
[Bug][v4.0.2] False negative for "Force update" render reason on Profiler

### ISSUE THREAD

**Issue by marconi1992** [preactjs/preact-devtools#343]
Hey folks 👋. Yesterday 7th May I started to get a false negative render reason for `Force update` in a memorized component when its pros didn't change.

**Browser**: Chrome `101.0.4951.54`
**Preact Dev Tools Version:**: `v4.0.2`

**Previous Behaviour**: In the version `v1.4.4` the render reason for `Memo(Button)` is `Parent updated` (This is expected because the state for the parent component  `Part1` changed). Also, the child component `Memo` didn't appear in the "Ranked" chart, it didn't render at all. 

**Current Behavior**: In the version `v4.0.2` the render reason for `Memo(Button)` is `Force update`, and it tells the `Button` component was rendered too but I was able to confirm is not being rendered at all.

Here is the component I was using to test: https://github.com/marconi1992/preact-redux-performance/blob/b9c0d962ddac02bb3d10e15a152543ee279d1a7b/src/routes/part-1/solution.jsx

Version `v4.0.2`

<img width="801" alt="image" src="https://user-images.githubusercontent.com/11670923/167298715-476fae17-9f1d-46f1-8067-d44357bce641.png">

Version `v1.4.4`

<img width="803" alt="image" src="https://user-images.githubusercontent.com/11670923/167298758-71fa7e06-a614-4097-aeb6-933a0a0919ee.png">

`

**Comment by marconi1992** [comment]
FWIW the issue is present in the `v4.0.1` version too

**Comment by marconi1992** [comment]
Hey @marvinhagemeister pinging you in this issue related to the latest `v4.x.x` release.

**Comment by marvinhagemeister** [comment]
Thanks for reporting this issue. I can confirm it on my end in one of my projects. Will take a look.
