### ISSUE TITLE
weird behavior with providers

### ISSUE THREAD

**Issue by AEnterprise** [preactjs/preact-devtools#35]
seems to be some weird interaction between the dev tools and providers passing things around, for some reason it first shows values but then turns them into null visually

![2019-12-09_21-24-21](https://user-images.githubusercontent.com/5206666/70471696-018fae00-1ace-11ea-9769-61d5b2bf4fc4.gif)

**Comment by marvinhagemeister** [comment]
Fixed with #179 :tada:
