### ISSUE TITLE
Newest update breaks my Preact app

### ISSUE THREAD

**Issue by oliverfindl** [preactjs/preact-devtools#352]
Hello,

since few days ago every interaction with my Preact app breaks whole app if this extension is enabled. If I disable it, my Preact app works as expected. I can see this message in webpage console.

![Screenshot from 2022-05-11 19-49-31](https://user-images.githubusercontent.com/33978096/167914768-ffe71787-6101-45c5-a27e-0d7dc44a908b.png)

Thanks.

**Comment by marvinhagemeister** [comment]
@oliverfindl Thanks for reporting this issue. With the stack trace I was able to reproduce the issue and create a fix. Will publish a new version soon 👍

**Comment by marvinhagemeister** [comment]
FYI: Until the release is out you can disable the `Highlight Updates` feature in the settings panel. That's what's causing the crash.

**Comment by oliverfindl** [comment]
@marvinhagemeister:

Thanks, this solution with disabling `Highlight Updates` fixes usage of my Preact app.
