### ISSUE TITLE
Props of last component when changing selceion

### ISSUE THREAD

**Issue by sventschui** [preactjs/preact-devtools#37]
When first selecting component A and then component B, the props view shows the props of B as being edited with the values of A. See:

	

![ezgif-6-1913f9d01224](https://user-images.githubusercontent.com/512692/70473395-410bc980-1ad1-11ea-9682-4cf727ab966e.gif)

**Comment by marvinhagemeister** [comment]
Fixed with 0842bf108bc3190f5c9f0324c2f5d028a1fdf29d :tada:
