### ISSUE TITLE
Next.js - This page doesn't seem to be using Preact

### ISSUE THREAD

**Issue by pronevich** [preactjs/preact-devtools#39]
I replaced React to Preact in Next.js app, but preact-devtools not detected Preact.

**Comment by marvinhagemeister** [comment]
Did you include `preact/debug` somewhere? And make sure you're using Preact `10.1.0` or newer.

**Comment by pronevich** [comment]
Thank you! In the beginning of next.js page should be added: 

```js
if (typeof window !== "undefined" && process.env.NODE_ENV === "development") {
  require("preact/debug");
}
```
