### ISSUE TITLE
Is there a way to use/config Preact Devtools with Deno + FeshApp?

### ISSUE THREAD

**Issue by og-dev** [preactjs/preact-devtools#427]
`preact devtools always shows "This page doesn't seem to use Preact"`

I've tried all recommendations but I can't get it to work.

Deno: `1.25`
Preact: `10.10.6`
FreshApp: `1.0.2`

**Comment by marvinhagemeister** [comment]
Yup, the [PR for adding devtools](https://github.com/denoland/fresh/pull/639) automatically to fresh when run in dev mode was merged a few days ago. The next release of fresh will support that out of the box. Currently just waiting for them to release a new version.
