### ISSUE TITLE
state dislocate in custom hook

### ISSUE THREAD

**Issue by comewithl** [preactjs/preact-devtools#433]
preact:  10.11.1
chrome: 106.0.5249.119
OS: MAC
<img width="601" alt="image" src="https://user-images.githubusercontent.com/16094594/197993681-8cdeab09-e7e3-4733-bf79-fae5a5e9037b.png">

the first state is in the same line with the custom hook, but the first state value in the next line.

**Comment by comewithl** [comment]
这是来自洪俊贤的自动回复邮件。

**Comment by marvinhagemeister** [comment]
Submitted a new version of the extension to browser vendors. Should be live in a couple of days and browsers typically auto-update to the new version.
