### ISSUE TITLE
What is content-script.js and why must it repeatedly tell me it is running.

### ISSUE THREAD

**Issue by xXACCEXx** [preactjs/preact-devtools#467]
Seems like there is a stray console log being injected in a page terminal.
Feels like this log is redundant and poluting. 

![image](https://user-images.githubusercontent.com/13444599/223032897-64cad84b-88ba-40c3-80bd-8ac64bd12980.png)

**Comment by marvinhagemeister** [comment]
Apologies, just noticed it myself. Looks like I accidentally published the debug build instead of the production one for chrome.

**Comment by xXACCEXx** [comment]
Oops. No drama. Thanks for the fast turn around!
