### ISSUE TITLE
Website: Version null

### ISSUE THREAD

**Issue by JajarGaming** [preactjs/preact-devtools#478]
![image](https://user-images.githubusercontent.com/71441748/236662841-3923c10d-44aa-4918-acf7-af1156d71159.png)

**Comment by JajarGaming** [comment]
I would've fixed the bug myself, but not sure where the code is located

**Comment by marvinhagemeister** [comment]
Whoops, thanks for reporting this! Looks like GitHub's API returned an unexpected value when the last release of DevTools was made. The code for that page is in the `gh-pages` branch. Pushed a commit that fixes it.
