### ISSUE TITLE
The extension couldn't detect deno fresh

### ISSUE THREAD

**Issue by ngdangtu-vn** [preactjs/preact-devtools#481]
The install process is very simple with just `import "preact/debug";` right? So I put it in `dev.ts` file like this:

```
#!/usr/bin/env -S deno run -A --watch=static/,routes/
import "preact/debug";

import dev from "$fresh/dev.ts";

await dev(import.meta.url, "./main.ts");
```

I tried this on Firefox & Chrome, none of them work. Did I missing something?

**Comment by marvinhagemeister** [comment]
Preact DevTools works out of the box with Fresh. The `preact/debug` import is already added by Fresh automatically so there is no need to do that. If it's not showing up for you than I'd consider that a bug in Fresh.

**Comment by marvinhagemeister** [comment]
Yeah can confirm that it's an issue in Fresh. Filed an issue there https://github.com/denoland/fresh/issues/1461
