### ISSUE TITLE
Suspense causes child elements to not appear.

### ISSUE THREAD

**Issue by pmkroeker** [preactjs/preact-devtools#76]
We started this conversation in #38, but I found the root cause of the issue that I was having and it was separate from the initial scope of that issue.

When using `Suspense/lazy` with the devtools, you end up with no children appearing in the devtools:
![image](https://user-images.githubusercontent.com/10147685/74047014-7ecb8800-4984-11ea-8661-e1bdaad17191.png)

Removing the lazy and suspense portions returns the desired functionality to the devtools.

I tried a to create a [reproduction](https://codesandbox.io/s/devtools-suspense-jzdl2) of the issue but for some reason using suspense seems to throw and error, preventing the app from correctly showing the issue.

I will continue to try and make the codesandbox work properly to demonstrate the issue as clearly as possible.

**Comment by marvinhagemeister** [comment]
That's awesome, I'll take a look. The reason the codesandbox is throwing an error is that the `lazy` component doesn't receive a function.

```jsx
// Wrong, import immediately runs after parsing this file
const LazySecond = lazy(import("./SecondRoute").then(m => m.SecondRoute));

// Correct, note the function wrapper.
const LazySecond = lazy(() => import("./SecondRoute").then(m => m.SecondRoute));
```

**Comment by pmkroeker** [comment]
Oh right, so used to TS spotting these. Fixing now.

**Comment by marvinhagemeister** [comment]
@pmkroeker Just checked again with the latest version of the extension (0.2.0, will be up in Chrome Webstore shortly) and I can confirm that this is fixed :tada: The extension correctly displays children of a `Lazy` component :100:

**Comment by pmkroeker** [comment]
Just wanted to quickly confirm that Chrome now uses version 0.2.0 and this works great! Thanks @marvinhagemeister!
