### ISSUE TITLE
No props displayed

### ISSUE THREAD

**Issue by donkeyDau** [preactjs/preact-devtools#79]
When activating the dev tools I can see the tree of components but no props are displayed at any component.

![preact_dev_tools](https://user-images.githubusercontent.com/17231336/75764169-c227d500-5d3d-11ea-81d0-6e5b42bc96b8.png)

The log console tells also `too much recursion`. I can see the memory usage rising until this message occurs then it suddenly drops and rises again.

My code looks like:

```
import 'preact/debug';
import { h } from 'preact';
import { useState } from 'preact/hooks';
import { ApolloProvider } from 'react-apollo';
import { IntlProvider } from 'preact-i18n';

import loginContext from './lib/loginContext';

import client, { startup } from './lib/apollo/client';
import App from './components/App/App';

import locales from './locales/en';

import './info';

const AppWrapper = () => {
  const [loggedIn, setLoggedIn] = useState(startup());

  return (
    <ApolloProvider client={client}>
      <IntlProvider definition={locales}>
        <loginContext.Provider value={{ loggedIn, setLoggedIn }}>
          <App />
        </loginContext.Provider>
      </IntlProvider>
    </ApolloProvider>
  );
};

export default AppWrapper;
```

**Comment by marvinhagemeister** [comment]
Sounds like there is an infinite loop somewhere. I'll take a look. Thanks for the detailed report 👍

**Comment by donkeyDau** [comment]
I can provide more information if necessary. We have some lib dependencies in that component. Most prominent https://github.com/react-bootstrap-table/react-bootstrap-table2 with rendered components in cells.

When I look closer now: The memory issue occurs only on one component. The "no props" issue is  present in our whole application.

**Comment by marvinhagemeister** [comment]
Alright, I think I found everything. Submitted a new version `0.1.3` to all extension stores, but it may take a good while until they're through the approval queue :slightly_smiling_face:

**Comment by marvinhagemeister** [comment]
@donkeyDau The extension was approved today in all stores and updates should be distributed over the day. Let me know if there are further issues 🙂

**Comment by donkeyDau** [comment]
@marvinhagemeister I've tried version 0.1.3 The props issue is solved. But still have heavy memory increases when displaying components using https://github.com/react-bootstrap-table/react-bootstrap-table2 I'll investigated it further (had not time yet) if the recursion error occurs or any other message. I will let you know.

**Comment by donkeyDau** [comment]
Totally forgot: Thanks a lot! This was a very quick response to the issue. I appreciated this very much.

**Comment by marvinhagemeister** [comment]
@marvinhagemeister Happy to have squashed this bug for good :raised_hands: To be honest I haven't done any performance or memory optimizations so far. Off the top of my head I can think of a few places where we keep more than necessary in memory when it comes to props.
