### ISSUE TITLE
Add Usage section to web page

### ISSUE THREAD

**Issue by 38elements** [preactjs/preact-devtools#96]
Since some people does not add `import "preact/debug";`, 
I think it may be better to add [Usage section](https://github.com/preactjs/preact-devtools#usage) to [web page](https://preactjs.github.io/preact-devtools/).

**Comment by marvinhagemeister** [comment]
Good idea! Added it with https://github.com/preactjs/preact-devtools/commit/d4019c7ef8d3c96a49a6ba71de315bcb7e52a204 :tada:
